env_files = [".env"]

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--out-dir", "sdk/wasm"]

[tasks.create-wasm-link]
command = "yarn"
args = ["--cwd", "./sdk/wasm", "link"]

[tasks.link-wasm]
command = "yarn"
args = ["--cwd", "./examples/nextjs", "link", "rollbar-sdk"]

[tasks.before-build-node]
command = "yarn"
args = ["--cwd", "./sdk/node", "install"]

[tasks.build-node]
command = "yarn"
args = ["--cwd", "./sdk/node", "build"]
dependencies = ["before-build-node"]

[tasks.create-node-link]
command = "yarn"
args = ["--cwd", "./sdk/node", "link"]

[tasks.link-node]
command = "yarn"
args = ["--cwd", "./examples/nodejs", "link", "rollbar-node"]

[tasks.before-nextjs-example]
command = "yarn"
args = ["--cwd", "./examples/nextjs", "install"]

[tasks.run-nextjs-example]
command = "yarn"
args = ["--cwd", "./examples/nextjs", "dev"]
dependencies = [
  "build-wasm",
  "create-wasm-link",
  "link-wasm",
  "before-nextjs-example",
]

[tasks.before-nodejs-example]
command = "yarn"
args = ["--cwd", "./examples/nodejs", "install"]

[tasks.run-nodejs-example]
command = "node"
args = ["./examples/nodejs/index.js"]
dependencies = [
  "before-nodejs-example",
  "build-node",
  "create-node-link",
  "link-node",
]

[tasks.generate-cpp-header]
command = "cxxbuild"
args = ["src/cpp.rs", "--header", "--output", "sdk/cpp/rollbar.h"]

[tasks.generate-cpp-file]
command = "cxxbuild"
args = ["src/cpp.rs", "--output", "sdk/cpp/rollbar.cpp"]

[tasks.build-cpp]
command = "g++"
args = ["--cwd", "./sdk/node", "build"]
dependencies = ["before-build-node"]
