env_files = [".env"]

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--out-dir", "../lib/wasm", "rollbar"]

[tasks.create-wasm-link]
command = "yarn"
args = ["--cwd", "./lib/wasm", "link"]

[tasks.link-wasm]
command = "yarn"
args = ["--cwd", "./examples/nextjs", "link", "rollbar"]

[tasks.before-build-node]
command = "yarn"
args = ["--cwd", "./lib/node", "install"]

[tasks.build-node]
command = "yarn"
args = ["--cwd", "./lib/node", "build"]
dependencies = ["before-build-node"]

[tasks.create-node-link]
command = "yarn"
args = ["--cwd", "./lib/node", "link"]

[tasks.link-node]
command = "yarn"
args = ["--cwd", "./examples/nodejs", "link", "rollbar-node"]

[tasks.before-nextjs-example]
command = "yarn"
args = ["--cwd", "./examples/nextjs", "install"]

[tasks.run-nextjs-example]
command = "yarn"
args = ["--cwd", "./examples/nextjs", "dev"]
dependencies = [
  "build-wasm",
  "create-wasm-link",
  "link-wasm",
  "before-nextjs-example",
]

[tasks.before-nodejs-example]
command = "yarn"
args = ["--cwd", "./examples/nodejs", "install"]

[tasks.run-nodejs-example]
command = "node"
args = ["./examples/nodejs/index.js"]
dependencies = [
  "before-nodejs-example",
  "build-node",
  "create-node-link",
  "link-node",
]

[tasks.make-cpp-workspace]
command = "mkdir"
args = ["-p", "build"]

[tasks.prepare-cpp-workspace]
command = "cmake"
cwd = "build"
args = [".."]
dependencies = ["make-cpp-workspace"]

[tasks.compile-cpp-example]
command = "make"
cwd = "build"
dependencies = ["prepare-cpp-workspace"]

[tasks.run-cpp-example]
command = "build/examples/cpp/example-cpp"
dependencies = ["compile-cpp-example"]
