[tasks.prepare-node]
command = "yarn"
args = ["--cwd", "node", "install"]

[tasks.build-node]
command = "yarn"
args = ["--cwd", "node", "build"]

[tasks.link-node]
command = "yarn"
args = ["--cwd", "node", "link"]

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--out-dir", "wasm"]

[tasks.link-wasm]
command = "yarn"
args = ["--cwd", "wasm", "link"]

[tasks.build]
dependencies = ["build-node", "build-wasm"]

[tasks.prepare-dev]
dependencies = ["prepare-node", "build-node", "link-node", "build-wasm", "link-wasm"]
