[package]
name = "rollbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["staticlib"]

[dependencies]
libc = "0.2.126"

[build-dependencies]
cbindgen = "0.23.0"
